### ISSUE TITLE
Compilation Warning 

### ISSUE THREAD

**Issue by dyoann** [AigangNetwork/aigang-platform-contracts-insurance#4]
contracts/utils/Strings.sol:8:20: Warning: This function only accepts a single "bytes" argument. Please use "abi.encodePacked(...)" or a similar function to encode the data.
            return keccak256(_a) == keccak256(_b);
                   ^-----------^
contracts/utils/Strings.sol:8:20: Warning: The provided argument of type string memory is not implicitly convertible to expected type bytes memory.
            return keccak256(_a) == keccak256(_b);
                   ^-----------^
Maybe check : 
 https://ethereum.stackexchange.com/questions/50551/solidity-how-to-get-a-bytes32-keccak256-hash-of-an-address-and-2-uint256-variab?rq=1

Maybe it's also related to my environement, I don't know :-)

**Comment by dariusdev** [comment]
This is related newer solidity version. Fixed 👍
